# SPDX-License-Identifier: Apache-2.0
#
# Composite action: hardens the runner and checks out the default branch.
# Used by bot workflows (on-comment, on-commit, on-pr) to centralise action
# versions and avoid running contributor-controlled code with write tokens.

name: "Setup Bot Environment"
description: "Hardens the runner and checks out the default branch for bot scripts"

runs:
  using: "composite"
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
      with:
        egress-policy: audit

    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: ${{ github.event.repository.default_branch }}
